### ISSUE TITLE
CSS Gradients Preview: No preview when language mode is set to PostCSS

### ISSUE THREAD

**Issue by ehoogeveen-medweb** [romainmenke/vscode-extensions#2]
Hi, I'm using [PostCSS Intellisense and Highlighting](https://marketplace.visualstudio.com/items?itemName=vunguyentuan.vscode-postcss) (and was previously using [PostCSS Language Support](https://marketplace.visualstudio.com/items?itemName=csstools.postcss) which unfortunately does not show color previews).

One of the steps in using this extension is setting the file association to postcss: `"files.associations": { "*.css": "postcss" }`.

Unfortunately it looks like the CSS Gradients Preview extension only works when the language mode is CSS (or at least, it doesn't appear to work with PostCSS). I haven't tested CSSTools Design Tokens but it might have the same problem.

**Comment by romainmenke** [comment]
That is actually working as designed :)

PostCSS is an extensible parser with a rich plugin ecosystem.
But it is not a language or a CSS syntax flavour.
Everyone creates their own variant by choosing certain plugins.

Because it is not a language it is also not possible to support `postcss` as a language identifier.

-----

I personally just use native CSS and the `css` language identifier.
This ensures that all extensions to help authoring CSS work as expected.

**Comment by ehoogeveen-medweb** [comment]
That's unfortunate. I use nesting-rules from postcss-preset-env as well as a few other PostCSS plugins, so if I use native css then VSCode can't parse it. Actually it looks like PostCSS Intellisense and Highlighting doesn't require the `files.associations` thing, it just sets the language mode to PostCSS regardless, but either way the gradient preview extension doesn't trigger.

**Comment by andrejilderda** [comment]
I unfortunately run into the same issue for the `Design Tokens`-extension. :(

**Comment by romainmenke** [comment]
Yes, still working as intended.
PostCSS is not a language.

If I were to add this I would get endless bug reports of people running into issues.
I don't have the capacity to handle any of that :/

The only good setup is Sass, Less, CSS,...
These plugins are designed for CSS.
